### PR TITLE
Remove CVS related contents

### PR DESCRIPTION
**Pull request by conao3**
Hi, I'm working on https://github.com/wanderlust/wanderlust/issues/184.
First, I remove obsoleted CVS related contents to clean project.

### CODE REVIEW

**Comment by ikazuhiro** [comment]
Sorry, I've forgotten to push document updates.  Please rebase.

**Comment by conao3** [comment]
you have rewrite CVS section with GitHub?
This PR suggests removing CVS section, it is useless now, I think.

**Comment by ikazuhiro** [comment]
> you have rewrite CVS section with GitHub?

Yes.

> This PR suggests removing CVS section, it is useless now, I think.

Your PR contains change of `Makefile`.  Can I ignore it?

**Comment by conao3** [comment]
OK, discard changes on texi, then I force-push.

**Comment by ikazuhiro** [comment]
Merged, thank you.

**Comment by conao3** [comment]
Thanks.

**Pull request closed without merging**
