### PR TITLE
Feature/cleanup texi

### PR DESCRIPTION
**Pull request by egh**
First, I removed the `*.sgml` files, because the sinfo format used is a custom format meant to be processed by sinfo.el, which uses the obsolete sgmls program. I spent some time trying to get this to work and failed. I don't see any advantage in keeping these and think we should switch to using .texi as the master file, or choose another format.

Second, I fixed the `mime-en.texi` file so that it can be processed by `texi2any`, the replacement for `makeinfo`.

Third, I corrected the encoding and title for `mime-ja.texi`. I could delete the broken crossreferences in this file as well, but if somebody who reads Japanese can correct them that would probably be better.

### CODE REVIEW

**Comment by ikazuhiro** [comment]
Can't `@documentencoding` be set to `iso-2022-jp`?  `7bit-jis` is exactly different coding system from `iso-2022-jp`.

**Comment by egh** [comment]
Thanks for the fix. I don't know anything about Japanese encoding, so I used the first thing that worked. I changed it to `iso-2022-jp`.

**Comment by ikazuhiro** [comment]
Thank you.  I will update Japanese document later.

**Comment by egh** [comment]
Thank you for all the merges!

**Pull request merged**
