### PR TITLE
Only quote file name using shell-quote-argument if necessary to avoid double quoting

### PR DESCRIPTION
**Pull request by egh**
See http://thread.gmane.org/gmane.mail.wanderlust.general.japanese/8065

### CODE REVIEW

**Comment by ikazuhiro** [comment]
I think `%s` should not be quoted in `mailcap` file.  Please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=745141#17.
Even if FLIM will support `'%s'`, your code can't handle filename which contains `'` nor escaped `'` such as `\'%s`.  At least the former should be supported.

**Comment by egh** [comment]
Thank you. I will look into correcting this issue upstream (my ubuntu `/etc/mailcap` contains many entries with `'%s'`).

What do you think about the following?

```
;; if the situation (wrongly) quotes the argument, fix it
(if (eq ?' (aref mtext (- i 2)))
    (concat "'" (shell-quote-argument file) "'")
  (shell-quote-argument file)))
```

This simply undoes the quotes by unquoting them.

I do not see any instances of `\'%s` in my `/etc/mailcap`, only `'%s'`, so I don't see a need to address this.

**Comment by ikazuhiro** [comment]
Fixed at https://github.com/wanderlust/flim/commit/94ea7b84a099b0dfac7f6b7452c51e826542be4e, but not tested for the case.

**Comment by egh** [comment]
Thank you!

**Pull request closed without merging**
